# Generated by Django 5.0.2 on 2025-09-22 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retention_days', models.IntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')], default=90, help_text='Automatically delete my data after specified days')),
                ('allow_sentiment_analysis', models.BooleanField(default=True, help_text='Enable AI sentiment analysis of my standup submissions')),
                ('allow_ai_analysis', models.BooleanField(default=True, help_text='Allow AI analysis of standup data for insights and summaries')),
                ('allow_team_analytics', models.BooleanField(default=True, help_text='Include my data in team-wide analytics and insights')),
                ('allow_voice_processing', models.BooleanField(default=False, help_text='Allow voice input processing and transcription')),
                ('allow_external_integrations', models.BooleanField(default=True, help_text='Allow integration with external tools (GitHub, Jira)')),
                ('anonymous_mode', models.BooleanField(default=False, help_text='Hide identifying information in team analytics')),
                ('github_connected', models.BooleanField(default=False, help_text='GitHub integration connection status')),
                ('github_integration_enabled', models.BooleanField(default=False, help_text='Enable GitHub integration for work item tracking')),
                ('jira_connected', models.BooleanField(default=False, help_text='Jira integration connection status')),
                ('jira_integration_enabled', models.BooleanField(default=False, help_text='Enable Jira integration for work item tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
