# Generated by Django 5.0.2 on 2025-09-22 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('transcription', 'Speech to Text Transcription'), ('sentiment_analysis', 'Sentiment Analysis'), ('summary_generation', 'Summary Generation'), ('entity_extraction', 'Entity Extraction'), ('intent_classification', 'Intent Classification')], max_length=30)),
                ('input_text', models.TextField()),
                ('result_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Processing Result',
                'verbose_name_plural': 'AI Processing Results',
                'db_table': 'ai_processing_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'processing_type'], name='ai_processi_user_id_fd43af_idx'), models.Index(fields=['status', 'created_at'], name='ai_processi_status_df0e0c_idx')],
            },
        ),
    ]
